version: "3.8"
services:
  gitlab-server:
    image: "gitlab/gitlab-ce"
    container_name: gitlab-server
    hostname: "gitlab.jakubhalik.org"
    ports:
      - "8081:80"
      - "9443:443"
      - "922:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        external_url 'https://gitlab.jakubhalik.org'
        puma['work_processes'] = 2
    volumes:
      - "/srv/gitlab/config:/etc/gitlab"
      - "/srv/gitlab/logs:/var/log/gitlab"
      - "/srv/gitlab/data:/var/opt/gitlab"
      - "/etc/letsencrypt:/etc/letsencrypt"
