version: '3.9'
services:
 gitlab:
   image: gitlab/gitlab-ee:latest
   container_name: gitlab
   restart: always
   hostname: 'gitlab.jakubhalik.org'
   environment:
     GITLAB_HOME: /srv/gitlab
     GITLAB_OMNIBUS_CONFIG: |
       external_url 'https://gitlab.jakubhalik.org'
       nginx['ssl_certificate'] = "/etc/letsencrypt/live/gitlab.jakubhalik.org/fullchain.pem"
       nginx['ssl_certificate_key'] = "/etc/letsencrypt/live/gitlab.jakubhalik.org/privkey.pem"
   ports:
     - '80:80'
     - '443:443'
     - '22:22'
   volumes:
     - '/srv/gitlab/config:/etc/gitlab'
     - '/srv/gitlab/logs:/var/log/gitlab'
     - '/srv/gitlab/data:/var/opt/gitlab'
     - '/etc/letsencrypt:/etc/letsencrypt'
   shm_size: '256m'

